#! /bin/bash
{
    # define variables
    OLD_USER=$(id -un)
    OLD_GROUP=$(id -gn)

    VAGRANT_VERSION="1.7.2"
    VAGRANT_URL="https://dl.bintray.com/mitchellh/vagrant/vagrant_"${VAGRANT_VERSION}"_x86_64.deb"
    VAGRANT_PACKAGE="vagrant.deb"

    KERNEL_VERSION=$(uname -r)

    PIP_URL="https://bootstrap.pypa.io/get-pip.py"
    
    RUGBY_ROOT="/opt"
    RUGBY_CORE="${RUGBY_ROOT}/Rugby"
    RUGBY_SERVER="${RUGBY_ROOT}/Rugby-Server"
    RUGBY_TESTS="${RUGBY_ROOT}/Rugby-Tests"
    RUGBY_PLAYBOOKS="${RUGBY_ROOT}/Rugby-Playbooks"
    RUGBY_VM_LOGS="${RUGBY_ROOT}/VM_Logs"


    # clear any previous sudo permission
    sudo -k

    # run inside sudo
    sudo sh <<SCRIPT

# update sources
apt-get update

# install vagrant and virtualbox
# install dpkg and virtualbox
apt-get install -y dpkg-dev virtualbox-dkms

# install vagrant
wget "${VAGRANT_URL}" -v -O "${VAGRANT_PACKAGE}"
dpkg -i "${VAGRANT_PACKAGE}"
rm "${VAGRANT_PACKAGE}"

# install linux headers
apt-get -y install "linux-headers-${KERNEL_VERSION}"

dpkg-reconfigure virtualbox-dkms

# install python-dev and pip
apt-get -y install python-dev

# install pip
wget -qO- "${PIP_URL}" | python -

# install virtualenv
pip install virtualenv

# install git
apt-get -y install git

# Clone project repos
git clone https://github.com/RugbyTeam/Rugby "${RUGBY_CORE}"
git clone https://github.com/RugbyTeam/Rugby-Server "${RUGBY_SERVER}"
git clone https://github.com/RugbyTeam/Rugby-Tests "${RUGBY_TESTS}"
git clone https://github.com/RugbyTeam/Rugby-Playbooks "${RUGBY_PLAYBOOKS}"

mkdir -p ${RUGBY_VM_LOGS}

chown -R "${OLD_USER}:${OLD_GROUP}" "${RUGBY_CORE}" "${RUGBY_SERVER}" "${RUGBY_TESTS}" "${RUGBY_PLAYBOOKS}" "${RUGBY_VM_LOGS}"
SCRIPT

# create and activate virtualenv
virtualenv "${RUGBY_CORE}/venv"
. "${RUGBY_CORE}/venv/bin/activate"

# install dependencies
export PYTHONPATH="${RUGBY_CORE}"
pip install -r "${RUGBY_CORE}/requirements.txt"
pip install -r "${RUGBY_SERVER}/requirements.txt"

# apply patch to vagrant
TO_PATCH="${PYTHONPATH}/venv/lib/python2.7/site-packages/vagrant/__init__.py"
PATCH="${PYTHONPATH}/patches/vagrant_quiet_logging_issue.patch"
patch "${TO_PATCH}" < "${PATCH}"

# add upstart service

    # run inside sudo
    sudo sh <<SCRIPT
cp rugby.conf /etc/init
initctl reload-configuration
SCRIPT

echo "Installation Successful!"
}
